### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by Anirudh257** [HeCraneChen/3D-Crowd-Pose-Estimation-Based-on-MVG#2]
Thanks for releasing your code!!

It will be great if you could add additional steps about how to run the code and a demo file as well.

**Comment by HeCraneChen** [comment]
> Thanks for releasing your code!!
> 
> It will be great if you could add additional steps about how to run the code and a demo file as well.

This is a 3-step approach. Each step should be self contained if paths are correctly pointing at the images required. (1) 2D pose detection(download the data from their official websites first, for example Wildtrack can be downloaded at “https://www.epfl.ch/labs/cvlab/data/data-wildtrack/”), (2) matching(the folder named matching, there are some paths in the demo pointing to the images you downloaded, make sure you change the paths), (3) 3D reconstruction (the folder named optimization). Please let me know if there is any other question.

**Comment by Anirudh257** [comment]
Thanks a lot.
